### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-iOS-OSX#1332]
If you would like to contribute, please feel free to open a PR. We'll gladly look it over.

- [ ] [and Query](https://github.com/parse-community/Parse-SDK-JS/pull/367)
- [ ] [nor Query](https://github.com/parse-community/parse-server/pull/4768)
- [ ] [containedBy Query](https://github.com/parse-community/parse-server/pull/4766)
- [ ] [containsStartingWith Query](https://github.com/parse-community/parse-server/pull/3864)
- [ ] [sort option for near Queries](https://github.com/parse-community/parse-server/pull/4825)
- [ ] [query IncludeAll / include('*')](https://github.com/parse-community/parse-server/pull/4838)
- [ ] [fetch with include](https://github.com/parse-community/parse-server/pull/4845)
- [ ] [relative time query](https://github.com/parse-community/parse-server/pull/4289)

Please refer to the following if you need help getting started.

[Contribution Guidelines](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/CONTRIBUTING.md)
[Test Suite](https://github.com/parse-community/Parse-SDK-iOS-OSX/tree/master/Parse/Tests/Unit)
[Past Pull Requests](https://github.com/parse-community/Parse-SDK-iOS-OSX/pulls?q=is%3Apr+is%3Aclosed)

**Comment by flovilmart** [comment]
@dplewis should we open one issue for each one witht the according docs and mark them good first task etc...

**Comment by ShawnBaek** [comment]
fix UnitTest for OSX

**Comment by ShawnBaek** [comment]
Support SPM

**Comment by mtrezza** [comment]
Closing this 4 year old issue; if a feature is wanted, please open a dedicated issue for it.
