### ISSUE TITLE
Deprecate SDK in favor of Swift SDK

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1658]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Current Limitation

This is to discuss the potential future deprecation of the "Parse ObjC SDK" and "Parse ObjC Live Query SDK" in favor of the Parse Swift SDK.

### Feature / Enhancement Description

The main objective for maintaining the "Parse ObjC SDK" is to provide a SDK for the iOS / macOS (and related) ecosystems. Since the Parse Swift SDK does this, maintaining both is not resource efficient.

Questions to consider the deprecation:
- What features are available in the Parse ObjC SDK vs. Swift SDK?
- What features are available with a "different approach" in the Swift SDK and what is the impact of that difference in terms of migration, data & cost efficiency?

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by mtrezza** [comment]
@cbaker6 What do you think is the best way to get a feature comparison overview between the Parse Swift vs. ObjC SDK?

**Comment by cbaker6** [comment]
> What do you think is the best way to get a feature comparison overview between the Parse Swift vs. ObjC SDK?

The best way I can think of is populate the feature comparisons manually. You can use my old comment as a starter https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1356#issuecomment-779288554

It's worth mentioning that deprecating the Objective-C SDK will deprecate any Parse support for Objective-C language as the Swift SDK isn't designed to work with Objective-C.

**Comment by mtrezza** [comment]
> It's worth mentioning that deprecating the Objective-C SDK will deprecate any Parse support for Objective-C language as the Swift SDK isn't designed to work with Objective-C.

Yes, that is intended as [mentioned](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1658#issue-1332294425).

**Comment by mkandler** [comment]
@mtrezza the one thing holding me off from switching to the Swift SDK is that I won't have the ability to set a custom `fileUploader`
e.g.
```
configuration.fileUploadController = CustomUploadController.shared
```

This way I can upload files directly from my app to S3 and still store them as `PFFile`s. Doing this saves a photo-based app (like mine) a ton of money on Heroku dynos for `parse-server`, because otherwise the data needs to be uploaded to the server and then to S3, clogging up servers in the process.

Has anyone considered adding something like this to the Swift project? I combed through the code but couldn't find anything. Happy to help out so I'm not stuck on a deprecated version of the SDK! It's already available in the JavaScript SDK as well.

**Comment by mtrezza** [comment]
I suggest opening a feature request in the Parse Swift SDK.

**Comment by danielchangsoojones** [comment]
How fully fleshed out is the ParseSwiftSDK? 

Is it something I should be writing a new iOS (swift only) project in?
Or is it still a work in progress?

**Comment by cbaker6** [comment]
> How fully fleshed out is the ParseSwiftSDK?

A post with details on features between the two SDK's is here: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1356#issuecomment-779288554

> Is it something I should be writing a new iOS (swift only) project in?
> Or is it still a work in progress?

The Swift SDK has more features than the Objective-C SDK (and IMO all other Parse SDK's at this point). It also has a higher percentage of codecov (90%+) than the Objective C SDK. The [API documentation](http://parseplatform.org/Parse-Swift/release/documentation/parseswift/) is also better and there's more [runnable sample code](https://github.com/parse-community/Parse-Swift/tree/main/ParseSwift.playground/Pages) available. You can also use the [Swift SDK to write Parse Cloud Code](https://github.com/netreconlab/parse-server-swift), so there's no need to use the JS SDK anymore if you don't want to. So the choice of what SDK to use for a new project is completely up to your taste. 

If you choose to use the Objective-C SDK, you will just need to do what's needed to keep it up-to-date as individuals from the Parse PMC has stated they plan on deprecating the SDK. I've repeatedly been against deprecating the Objective-C SDK and believe the only reason it's occurring is because developers have not stepped up to maintain it. The SDK is still very powerful and built well, it's feature-set just isn't on-par with the Parse Server or Swift SDK.

**Comment by mtrezza** [comment]
The reason for the deprecation is explained in the first [post](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1658#issue-1332294425).

**Comment by cbaker6** [comment]
> This is incorrect. There are features missing, that's why we're compiling the migration guide.

This is your opinion, which you are open to. For anyone else, they can take whoever’s word they want. I stand on what I said. In addition, @mtrezza you cannot tell me what to say and not to say, you have zero influence over my words or contributions.

**Comment by mtrezza** [comment]
I'm confused. You just approved the PR to add a note about this missing feature to the migration guide?

**Comment by mtrezza** [comment]
We are currently re-evaluating the future of the Parse iOS SDK. In the meantime we are closing this issue to avoid further confusion, in case we decide to retract the deprecation of this SDK.
